---
kind: pipeline
type: kubernetes
name: server_webhook
steps:
- name: discord notification
  image: appleboy/drone-discord
  settings:
    secrets: [ webhook_id, webhook_secret ]
    message: "New version deployed! @everyone"
