---
kind: pipeline
type: kubernetes
name: Information
steps:
- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id: 699704720176054324
    webhook_token:
      from_secret: webhook_secret
