---
kind: pipeline
type: kubernetes
name: server_webhook
steps:
- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id: 699704720176054324
    secrets: [ webhook_id, webhook_secret ]
