---
kind: pipeline
type: kubernetes
name: server_webhook
steps:
- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id: 699704720176054324
    secrets: [ webhook_id, webhook_secret ]
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
