---
kind: pipeline
type: kubernetes
name: server_webhook
steps:
- name: discord notification
  image: appleboy/drone-discord
  settings:
    secrets: [ discord_webhook_id, discord_webhook_token ]
    message: "New version deployed! @everyone"
